use_frameworks!

platform :ios, '8.0'

target 'YACOAutoFitScreen_Example' do
  pod 'YACOAutoFitScreen', :path => '../'

  target 'YACOAutoFitScreen_Tests' do
    inherit! :search_paths

    
  end
end
